<?php

namespace App\Enums;

enum WordEnum:string {
    case Razon1 = 'le otorga tranquilidad, más no, necesariamente, rentabilidad. De allí que la clave radica en sacrificar un tanto el sosiego a favor de una mayor preocupación por la reducción de la razón corriente a cambio de una mayor rentabilidad. En concreto, el límite de la disminución de la razón corriente será el punto a partir del cual se empiece a perder oportunidades de ingresos netos, y a su vez, ese esfuerzo deberá implantarse, siempre y cuando el costo de capital (promedio ponderado del costo de oportunidad y de los gastos financieros) de los fondos internos de corto plazo sea mayor al gasto financiero de los fondos externos de corto plazo. Dicho de otro modo, si el costo de capital de los fondos internos de corto plazo es superior que el gasto financiero de los fondos externos de corto plazo, será mejor mover el negocio privilegiando el uso de los fondos externos, pero bajo la condición que esta medida no se traduzca en interrupciones de los ingresos del negocio o en pérdidas de oportunidades de rentabilidad.';
    case Razon2 = 'indica que es el momento de estudiar dos variables básicas: el costo de capital de los fondos internos de corto plazo frente a los gastos financieros de los fondos externos de corto plazo y las pérdidas de oportunidades de rentabilidad como efecto de tener un valor de activo corriente similar al del pasivo corriente. Solo después de este análisis, los líderes de la empresa deberán decidir en torno a subir, mantener o disminuir su ratio de razón corriente. Más que si la razón corriente (activo corriente entre pasivo corriente) debe ser mayor, igual o menor a 1, les debe interesar, simultáneamente, si les conviene utilizar más o menos fondos internos de corto plazo, y si la opción elegida les aumenta, mantiene o disminuye el aprovechamiento de oportunidades para aumentar la rentabilidad. Así, en cualquier alternativa, lo importante es que una mayor, igual o menor razón corriente, esta se constituya en un impulsor de la rentabilidad. En este camino, el límite de la disminución de la razón corriente será el punto a partir del cual se empiece a perder oportunidades de ingresos netos; y la frontera del aumento de la razón corriente será el deterioro de la rentabilidad derivado del mayor uso de fondos internos de corto plazo. Es decir, si el costo de capital de los fondos internos de corto plazo es inferior que el gasto financiero de los fondos externos de corto plazo, será mejor mover el negocio privilegiando el uso de los fondos internos, y por lo tanto, valdrá la pena aumentar la razón corriente, pero bajo la condición que esta medida no se traduzca en menor rentabilidad.';
    case Razon3 = 'indica que es el momento de estudiar dos variables básicas: el costo de capital de los fondos internos de corto plazo frente a los gastos financieros de los fondos externos de corto plazo y el monto que pierde la empresa como efecto de tener un valor de activo corriente menor al del pasivo corriente. Solo después de este análisis, los líderes de la empresa deberán decidir en torno a subir o mantener su ratio de razón corriente. Más que si la razón corriente (activo corriente entre pasivo corriente) debe ser mayor, igual o menor a 1, les debe interesar, simultáneamente, si les conviene utilizar mayor o la misma cantidad de fondos internos de corto plazo, y si la opción adoptada les aumenta, mantiene o disminuye el aprovechamiento de oportunidades para aumentar la rentabilidad. Así, en cualquier alternativa, lo importante es que una mayor o igual razón corriente, esta se constituya en un impulsor de la rentabilidad. En este camino, el límite de mantener similar razón corriente será la prolongación o el aumento de las pérdidas de oportunidades de ingresos netos; y la frontera del aumento de la razón corriente será el deterioro de la rentabilidad derivado del mayor uso de fondos internos de corto plazo. Es decir, si el costo de capital de los fondos internos de corto plazo es inferior que el gasto financiero de los fondos externos de corto plazo, será mejor mover el negocio privilegiando el uso de los fondos internos, y por lo tanto, valdrá la pena aumentar la razón corriente, pero bajo la condición que esta medida no se traduzca en menor rentabilidad.';
    case Rejected = 'rejected';
}
